
services:
  db:
    container_name: lamp-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp_demo
      MYSQL_USER: lamp_demo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s     
      retries: 5

  www:
    container_name: lamp-www
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1.1-apache
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./:/var/www/html"
    ports:
      - "85:80"
      - "443:443"
    networks:
      - lamp-docker

  phpmyadmin:
    container_name: lamp-phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:  
      - lamp-docker

networks:
  lamp-docker:
    driver: bridge
