services:
  db:
    image: mysql:latest
    container_name: mysql-IS436
    environment:
      MYSQL_ROOT_PASSWORD: is436
      MYSQL_DATABASE: IS436
      MYSQL_USER: root
      MYSQL_PASSWORD: is436
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
networks:
  mysql_network:
