
services:
  db:
    image: mysql:8.0  # Specify the version as needed
    container_name: mysql-IS436
    environment:
      MYSQL_DATABASE: IS436
      MYSQL_USER: user  # Use a non-root user
      MYSQL_PASSWORD: user_password  # Set a secure password for the user
      MYSQL_ROOT_PASSWORD: root_password  # Set a secure root password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql_network  # Connect to the network

volumes:
  db_data:

networks:
  mysql_network:
